# ============================================================
#  GRUNDEINSTELLUNGEN – hier trägst du deine Angaben ein
# ============================================================
title: "Konrad Nissen"
tagline: "MIDEM, Dresden University of Technology"
description: >
email: "konrad [punkt] nissen [at] tu-dresden [punkt] de"
author: "[Vorname] [Nachname]"

# Wird für Links auf der Startseite benutzt (leer lassen = kein Link/Button anzeigen)
orcid: "0009-0008-6314-3697"            # z. B. "0000-0000-0000-0000"
# google_scholar: ""   # z. B. "https://scholar.google.com/citations?user=xxxx"
github_username: "konradnissen"  # z. B. "deinname"
linkedin: "https://www.linkedin.com/in/konrad-nissen-2286b3166/"         # vollständige URL

# ============================================================
#  TECHNIK – normalerweise nicht verändern
# ============================================================
url: ""                     # wird von GitHub Pages automatisch gesetzt
baseurl: ""                 # nur nötig falls Repo NICHT "username.github.io" heißt,
                             # dann hier "/repo-name" eintragen

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

feed:
  path: blog/feed.xml

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
